apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: kubia:latest
      name: kubia
      imagePullPolicy: Never
      ports:
        - containerPort: 9999
          protocol: TCP